[colors-dark]
# Everforest Theme
background=2d353b
foreground=d3c6aa

# Selection and Cursor
selection-background=505a60
selection-foreground=9da9a0
cursor=d3c6aa 343f44
urls=7fbbb3

# Normal Colors (color palette 0-7)
regular0=343f44  # black
regular1=e67e80  # red
regular2=a7c080  # green
regular3=dbbc7f  # yellow
regular4=7fbbb3  # blue
regular5=d699b6  # magenta
regular6=83c092  # cyan
regular7=859289  # white

# Bright Colors (color palette 8-15)
bright0=868d80   # bright black
bright1=e67e80   # bright red
bright2=a7c080   # bright green
bright3=dbbc7f   # bright yellow
bright4=7fbbb3   # bright blue
bright5=d699b6   # bright magenta
bright6=83c092   # bright cyan
bright7=9da9a0   # bright white
